name: Build and Release macOS App

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build macOS arm64 package
        run: npm run package-mac-arm64 && npm run create-installer-mac-arm64

      - name: Build macOS x64 package
        run: npm run package-mac-x64 && npm run create-installer-mac-x64

      - name: Upload Release Asset arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./scripts/Perplexity-installer-arm64.app
          asset_name: Perplexity-installer-arm64-${{ github.ref_name }}.app
          asset_content_type: application/app

      - name: Upload Release Asset x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./scripts/Perplexity-installer-x64.app
          asset_name: Perplexity-installer-x64-${{ github.ref_name }}.app
          asset_content_type: application/app